// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxDLAQ59eA2REklEvLIqT3CqpZ0muk1Q',
    appId: '1:243668442453:web:278bfa517aae966262a3dc',
    messagingSenderId: '243668442453',
    projectId: 'learn-english-3e7bd',
    authDomain: 'learn-english-3e7bd.firebaseapp.com',
    storageBucket: 'learn-english-3e7bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFkHHvGfv5ipe4om18NPkMjt8X3FxMUw',
    appId: '1:243668442453:android:7f4e4df647939c1a62a3dc',
    messagingSenderId: '243668442453',
    projectId: 'learn-english-3e7bd',
    storageBucket: 'learn-english-3e7bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1NkQ6o3xBXhF8zSDOs0JTMYe713sRVZ4',
    appId: '1:243668442453:ios:2b0e68e4e779dfc162a3dc',
    messagingSenderId: '243668442453',
    projectId: 'learn-english-3e7bd',
    storageBucket: 'learn-english-3e7bd.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1NkQ6o3xBXhF8zSDOs0JTMYe713sRVZ4',
    appId: '1:243668442453:ios:2b0e68e4e779dfc162a3dc',
    messagingSenderId: '243668442453',
    projectId: 'learn-english-3e7bd',
    storageBucket: 'learn-english-3e7bd.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwxDLAQ59eA2REklEvLIqT3CqpZ0muk1Q',
    appId: '1:243668442453:web:9aa0019ba4eace8e62a3dc',
    messagingSenderId: '243668442453',
    projectId: 'learn-english-3e7bd',
    authDomain: 'learn-english-3e7bd.firebaseapp.com',
    storageBucket: 'learn-english-3e7bd.firebasestorage.app',
  );
}
